version: '3.4'

services:
    web:
        build: ./src
        ports:
        - 8000:8082
        command: uvicorn main:app --host 0.0.0.0 --port 8082 --reload
        volumes:
            - ./src:/usr/src/app
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
    worker:
        build: ./src
        # command: celery worker --app=worker.celery --loglevel=info --logfile=logs/celery.log
        command: celery --app=worker worker --loglevel=info
        volumes:
            - ./src:/usr/src/app
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
            - web
    redis:
        image: redis:6-alpine
    dashboard:
        build: ./src
        command: celery flower --app=worker.celery --port=5555 --broker=redis://redis:6379/0
        ports:
            - 8080:5555
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - redis
            - web
            - worker